flask/demo/myapp/__init__.py
#coding=utf-8
from flask import Flask,request,session
from myapp.extension import socketio,db,login_manager,pagedown,moment,\
                            bootstrap,babel,admin,toolbar,mogodb,mail,photos
import flask_whooshalchemyplus
from flask_uploads import configure_uploads
from config import config,Config
from celery import  Celery
from flask_sslify import SSLify
import re
celery = Celery(__name__,backend=Config.CELERY_RESULT_BACKEND,broker=Config.CELERY_BROKER_URL)



login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
def create_app(config_name):
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    from .mongo import mongo as mongo_blueprint
    from .socket_io import socket_io as socket_io_blueprint
    app = Flask(__name__)
    #判断客户端是否是手机
    @app.before_request
    def before_first_request():
        User_Agent = request.headers['User-Agent']
        is_mobile = re.findall('Mobile', User_Agent)
        if is_mobile:
             session['mobile_flags'] = 1
        else:
            session['mobile_flags']=0
    app.config['BABEL_DEFAULT_LOCALE']='zh_CN'
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    babel.init_app(app)
    bootstrap.init_app(app)
    configure_uploads(app, photos)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)
    login_manager.init_app(app)
    admin.init_app(app)
    socketio.init_app(app)
    #toolbar.init_app(app)
    mogodb.init_app(app)
    celery.conf.update(app.config)
    flask_whooshalchemyplus.init_app(app)

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(socket_io_blueprint)
    app.register_blueprint(mongo_blueprint,url_prefix='/mongo')
    sslify = SSLify(app)
    return app

flask/demo/myapp/admin/__init__.py
from .import views

flask/demo/myapp/admin/views.py
#coding=utf-8
from flask_admin import  BaseView, expose
from flask import url_for
from flask_login import current_user
from flask_admin.contrib.sqla import ModelView
from ..models import Post
from myapp.extension import db
import os as op
from myapp.extension import admin
from flask_admin.contrib.fileadmin import FileAdmin




class MyView(BaseView):
    #改函数返回真才能访问该导航
    def is_accessible(self):
        return current_user.is_authenticated  #用户登录返回真。
    # http://127.0.0.1:5000/welcome/my/
    @expose('/')
    def index(self):
        url = url_for('.view')
        return self.render('admin/home.html',url=url)
    #http://127.0.0.1:5000/welcome/my/view
    @expose('/view')
    def view(self):
        return self.render('admin/view.html')

class hello1(BaseView):
    # http://127.0.0.1:5000/welcome/test1/
    @expose('/')
    def index(self):
        return self.render('admin/hello1.html')
class hello2(BaseView):
    # http://127.0.0.1:5000/welcome/test2/
    @expose('/')
    def index(self):
        return self.render('admin/hello2.html')
class hello3(BaseView):
    # http://127.0.0.1:5000/welcome/test3/
    @expose('/')
    def index(self):
        url = url_for('my.view') #MyView.view函数
        return self.render('admin/hello3.html',url=url)





class UserView(BaseView):
    #改函数返回真才能访问该导航
    def is_accessible(self):
        return current_user.is_authenticated  #用户登录返回真。
    # http://127.0.0.1:5000/welcome/my/
    @expose('/')
    def index(self):
        url = url_for('.view')
        return self.render('admin/home.html',url=url)
    #http://127.0.0.1:5000/welcome/my/view
    @expose('/view')
    def view(self):
        return self.render('admin/view.html')

class MyV1(ModelView):
    def is_accessible(self):
        if current_user.is_authenticated :
            return True
        return False
    can_create = False

    column_labels = {
        'id':u'序号',
        'body' : u'文章',
        'timestamp':u'发布时间',
        'author_id':u'作者id'
    }
    column_list = ('id', 'body','timestamp','author_id')
    def __init__(self, session, **kwargs):
        super(MyV1, self).__init__(Post,session, **kwargs)



admin.add_view(MyView(name='新闻',endpoint='my'))
admin.add_view(hello1(name='Hello 1', endpoint='test1', category='信息'))
admin.add_view(hello2(name='Hello 2', endpoint='test2', category='信息'))
admin.add_view(hello3(name='Hello 3', endpoint='test3', category='信息'))
path = op.join(op.dirname(__file__), '../static/img')
print(path)
admin.add_view(FileAdmin(path, '/static/', name='文件',endpoint='file'))
admin.add_view(MyV1(db.session, name=u'管理新闻'))

flask/demo/myapp/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors
from ..models import Permission
@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

flask/demo/myapp/main/views.py
#coding=utf-8
from time import sleep
from flask import render_template, redirect, url_for,request,flash,abort,current_app,make_response,jsonify,session
from flask.ext.sqlalchemy import get_debug_queries
from . import main
from .forms import EditProfileForm,EditProfileAdminForm,PostForm,CommentForm
from .. import db
from flask_login import login_required,current_user
from ..models import User,Role,Post,Comment,Whoosh,Permission
from ..celery_email import sub
from ..decorators import admin_required, permission_required

#报告缓慢的数据库查询
@main.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['FLASKY_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
            'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n' %(query.statement, query.parameters, query.duration,query.context))
    return response

# @main.route('/test')
# def test():
#     r=sub.delay()
#     print(r.result)
#     print(r.successful())
#     print(r.backend)
#     i=0
#     while r.successful()==False:
#         i=i+1
#         sleep(4)
#         print(i)
#     return r.status

@main.route('/is_admin')
@login_required
@admin_required
def for_admins_only():
    return "For administrators!"

@main.route('/moderator')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def for_moderators_only():
    return "For comment moderators!"

@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('user.html', user=user)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        current_user.img=form.img.data
        db.session.add(current_user)
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    form.img.data=current_user.img
    return render_template('edit_profile.html', form=form)

@main.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        flash('The profile has been updated.')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)
@main.route('/user_img')
@login_required
def user_img():
    img  = User.query.filter_by(id=current_user.id).first()
    return img.img

@main.route('/img/<username>')
def img(username):
    try:
        img  = User.query.filter_by(username=username).first()
    except:
        pass
    else:img  = User.query.filter_by(username='chen').first()
    return img.img


@main.route('/', methods=['GET', 'POST'])
def index():
    form = PostForm()
    current_app.logger.debug('A value for debugging')
    current_app.logger.warning('A warning occurred (%d apples)', 42)
    current_app.logger.error('An error occurred')
    if current_user.can(Permission.WRITE_ARTICLES) and \
    form.validate_on_submit():
        post = Post(body=form.body.data,
        author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    if session.get('mobile_flags',None):
        return render_template('index.html', form=form, posts=posts,
                               show_followed=show_followed, pagination=pagination)
    return render_template('index.html', form=form, posts=posts,
                           show_followed=show_followed, pagination=pagination)

#编辑文章
@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
    not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        flash('The post has been updated.')
        return redirect(url_for('post', id=post.id))
    form.body.data = post.body
    return render_template('edit_post.html', form=form)
#取消关注路由
@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    if not current_user.is_following(user):
        flash('You are not following this user.')
        return redirect(url_for('.user', username=username))
    current_user.unfollow(user)
    flash('You are not following %s anymore.' % username)
    return redirect(url_for('.user', username=username))
#添加关注路由
@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    if current_user.is_following(user):
        flash('You are already following this user.')
        return redirect(url_for('.user', username=username))
    current_user.follow(user)
    flash('You are now following %s.' % username)
    return redirect(url_for('.user', username=username))
#查看被关注列表
@main.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp} for item in pagination.items]
    return render_template('followers.html', user=user, title="Followers of",
    endpoint='.followers', pagination=pagination,
    follows=follows)

@main.route('/followed-by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('followers.html', user=user, title="Followed by",
                           endpoint='.followed_by', pagination=pagination,
                           follows=follows)
#显示所有文章
@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*60)
    return resp

#只展示关注者的文章
@main.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp

#评论
@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                    post=post,
                    author=current_user._get_current_object())
        db.session.add(comment)
        flash('Your comment has been published.')
        return redirect(url_for('.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / \
        current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
                                        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
                                            error_out=False)
    comments = pagination.items
    return render_template('post.html', posts=[post], form=form,
    comments=comments, pagination=pagination)

@main.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
    page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
    error_out=False)
    comments = pagination.items
    return render_template('moderate.html', comments=comments,

flask/demo/myapp/mongo/views.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask.views import MethodView
from . import mongo
from myapp.mogomodels import Post
@mongo.route('/list')
def list():
    posts = Post.objects.all()
    return render_template('mongo/list.html', posts=posts)
@mongo.route('/detail/<slug>')
def detail(slug):
    post = Post.objects.get_or_404(slug=slug)
    return render_template('mongo/detail.html', post=post)

flask/demo/myapp/socket_io/__init__.py
from flask import Blueprint
socket_io = Blueprint('socket_io', __name__)
from . import views

flask/demo/myapp/socket_io/views.py
from flask import render_template,session
from .import socket_io
@socket_io.route('/msg/')
def msg():
    return render_template('socketio/msg.html')

flask/demo/myapp/templates/_comments.html
<div class="comment-body">
{% if comment.disabled %}
<p></p><i>This comment has been disabled by a moderator.</i></p>
{% endif %}
{% if moderate or not comment.disabled %}
{% if comment.body_html %}
{{ comment.body_html | safe }}
{% else %}
{{ comment.body }}
{% endif %}
{% endif %}
</div>
{% if moderate %}
<br>
{% if comment.disabled %}
<a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable',
id=comment.id, page=page) }}">Enable</a>
{% else %}
<a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable',
id=comment.id, page=page) }}">Disable</a>
{% endif %}
{% endif %}

flask/demo/myapp/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages(left_edge= 1 ,left_current=3,right_current=3,right_edge=1) %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

flask/demo/myapp/templates/_posts.html
    <ul class="posts">
        {% for post in posts %}
        <li class="post">
            <div class="profile-thumbnail">
                <a href="{{ url_for('.user', username=post.author.username) }}">
                    <img class="img-rounded profile-thumbnail" src="{{ url_for('main.img',username=post.author.username) }} "
                    style=" width: 40px;height: 40px;">
                </a>
            </div>
            <div class="post-content" style="padding-left: 0px;margin-left: 5px">
                <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
                <div class="post-author">
                    <a href="{{ url_for('.user', username=post.author.username) }}">
                    {{ post.author.username }}
                    </a>
                </div>
                <div class="post-body">
                    {% if post.body_html %}
                    {{ post.body_html | safe }}
                    {% else %}
                    {{ post.body }}
                    {% endif %}
                </div>
                <div class="post-footer">
                    {% if current_user == post.author %}
                    <a href="{{ url_for('.edit', id=post.id) }}">
                        <span class="label label-primary">Edit</span>
                     </a>
                    {% elif current_user.is_administrator() %}
                    <a href="{{ url_for('.edit', id=post.id) }}">
                        <span class="label label-danger">Edit [Admin]</span>
                    </a>
                    {% endif %}
                    <a href="{{ url_for('.post', id=post.id) }}">
                        <span class="label label-default">Permalink</span>
                    </a>
                    <a href="{{ url_for('.post', id=post.id) }}#comments">
                        <span class="label label-primary">
                        {{ post.comments.count() }} Comments
                        </span>
                    </a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>

flask/demo/myapp/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.can(Permission.MODERATE_COMMENTS) %}
                <li><a href="{{ url_for('main.moderate') }}">Moderate Comments</a></li>
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ url_for('main.img',username=current_user.username)}}" width="30px" height="30">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

flask/demo/myapp/templates/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Flasky - Edit Post{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1>Edit Post</h1>
    </div>
    <div>
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
{% endblock %}

flask/demo/myapp/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

flask/demo/myapp/templates/followers.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Flasky - {{ title }} {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }} {{ user.username }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>User</th><th>Since</th></tr></thead>
    {% for follow in follows %}
    {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username = follow.user.username) }}">
                <img class="img-rounded" src="{{ follow.user.img}}">
                {{ follow.user.username }}
            </a>
        </td>
        <td>{{ moment(follow.timestamp).format('L') }}</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint, username = user.username) }}
</div>
{% endblock %}

flask/demo/myapp/templates/moderate.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}Flasky - Comment Moderation{% endblock %}
{% block page_content %}
<div class="page-header">
<h1>Comment Moderation</h1>
</div>
{% set moderate = True %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
{{ macros.pagination_widget(pagination, '.moderate') }}
</div>
{% endif %}
{% endblock %}

flask/demo/myapp/templates/post.html
{% extends "base.html" %}
{% block title %}Flasky - Post{% endblock %}
{% block page_content %}
{% include '_posts.html' %}
{% endblock %}

flask/demo/myapp/templates/user.html
{% extends "base.html" %}
{% block title %}Flasky{% endblock %}
{% block page_content %}
    <div class="page-header">
        <div><img class="img-rounded profile-thumbnail" src="{{ url_for('main.img',username=user.username)}}" width="250" height="250"></div>
        <div class="profile-header">
        <h1>{{ user.username }}</h1>
        {% if user.name or user.location %}
            <p>
                {% if user.name %}{{ user.name }}{% endif %}
                {% if user.location %}
                From <a href="http://maps.google.com/?q={{ user.location }}">
                        {{ user.location }}
                    </a>
                {% endif %}
            </p>
        {% endif %}
        {% if current_user.is_administrator() %}
             <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>
        Member since {{ moment(user.member_since).format('L') }}.
        Last seen {{ moment(user.last_seen).fromNow() }}.
        </p>
        <p>
            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                {% if not current_user.is_following(user) %}
                <a href="{{ url_for('.follow', username=user.username) }}" class="btn btn-primary">Follow</a>
                {% else %}
                <a href="{{ url_for('.unfollow', username=user.username) }}" class="btn btn-default">Unfollow</a>
                {% endif %}
            {% endif %}
            <a href="{{ url_for('.followers', username=user.username) }}">Followers: <span class="badge">{{ user.followers.count() - 1 }}</span></a>
            <a href="{{ url_for('.followed_by', username=user.username) }}">Following: <span class="badge">{{ user.followed.count() - 1 }}</span></a>
            {% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %}
            | <span class="label label-default">Follows you</span>
            {% endif %}
        </p>
        {% if user == current_user %}
            <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">
            Edit Profile
            </a>
        {% endif %}

        {% if current_user.is_administrator() %}
            <a class="btn btn-danger" href="{{ url_for('.edit_profile_admin', id=user.id) }}">
            Edit Profile [Admin]
            </a>
        {% endif %}
    </div>
    </div>

{% endblock %}